### ISSUE TITLE
Implement prettier urls 

### ISSUE THREAD

**Issue by ajpiano** [bocoup/johnny-five.org#18]
I think it would be :100: if we had urls like

`http://johnny-five.org/api/compass/`

instead of

`http://johnny-five.org/api/compass.html`

This can be accomplished in the gruntfile by just changing things to output at "page/index.html" instead of "page.html"

**Comment by rwaldron** [comment]
Cool, will do

**Comment by rwaldron** [comment]
Same for examples?

**Comment by ajpiano** [comment]
Yeah, all pages

**Comment by rwaldron** [comment]
These are much nicer this way :)

**Comment by ajpiano** [comment]
:shower: :bath: :+1:
