### ISSUE TITLE
Hello World for Spark doesn't match figure

### ISSUE THREAD

**Issue by Resseguie** [bocoup/johnny-five.org#23]
On the home page, the hello world program for Spark Core uses `new five.Led(0)` but the example diagram seems to show it plugged in to `D7`.

The diagram also suggests the LED is plugged directly "into" the Spark as opposed to breadboarded. Was that a purposeful decision to simplify? Will it cause confusion?

**Comment by rwaldron** [comment]
Many are wrong. PR? 

Just update here: https://github.com/bocoup/johnny-five.org/blob/master/src/js/main.js#L4-L53
