### ISSUE TITLE
broken images

### ISSUE THREAD

**Issue by tkellen** [bocoup/johnny-five.org#30]
I checked every example page, here are the ones with broken images:

http://johnny-five.org/examples/led/
http://johnny-five.org/examples/led-blink/
http://johnny-five.org/examples/grove-sensor/
http://johnny-five.org/examples/tinkerkit-blink/
http://johnny-five.org/examples/tinkerkit-button/
http://johnny-five.org/examples/tinkerkit-continuous-servo/
http://johnny-five.org/examples/tinkerkit-linear-pot/
http://johnny-five.org/examples/tinkerkit-rotary/
http://johnny-five.org/examples/tinkerkit-thermistor/
http://johnny-five.org/examples/tinkerkit-tilt/
http://johnny-five.org/examples/tinkerkit-touch/
http://johnny-five.org/examples/motobot/
http://johnny-five.org/examples/nodebot/
http://johnny-five.org/examples/brat/

**Comment by rwaldron** [comment]
Ugh. These are all new images I think. Thanks.

**Comment by rwaldron** [comment]
cc @Resseguie

**Comment by tkellen** [comment]
n/p. just did the api docs, here are the ones with broken images:
http://johnny-five.org/api/animation/
http://johnny-five.org/api/joystick/

**Comment by rwaldron** [comment]
Thanks. I think I found the issue.

**Comment by rwaldron** [comment]
https://github.com/bocoup/johnny-five.org/commit/130d5891afa4cf0b99bdc7f9a622d5bdfbbffa7b

**Comment by Resseguie** [comment]
I had separated photo images from breadboard images in that last big example update.
