### ISSUE TITLE
broken external link

### ISSUE THREAD

**Issue by leobalter** [bocoup/johnny-five.org#34]
On http://johnny-five.org/api/led.digits/ the newegg link is 404ing

the broken link: http://www.newegg.com/Product/Product.aspx?Item=9SIA2C516T9999

**Comment by rwaldron** [comment]
https://github.com/bocoup/johnny-five.org#content-building

I fixed this one, but future content issues should be reported to their respective repo (or in the wiki case, just fix it)

**Comment by leobalter** [comment]
Thanks. I've found several broken internal links on the website related to the wiki content, I'll fix them.
