### ISSUE TITLE
clicking on the logo should take you to the home page

### ISSUE THREAD

**Issue by tkellen** [bocoup/johnny-five.org#36]
![screen shot 2015-04-08 at 12 42 55 pm](https://cloud.githubusercontent.com/assets/1004324/7052590/cc7cd2e2-ddec-11e4-88fb-42f9196286ff.png)

**Comment by rwaldron** [comment]
I almost thought this would be easy... cc @Wilto

**Comment by leobalter** [comment]
fixed by d040984
