### ISSUE TITLE
platform support - wireless tethering

### ISSUE THREAD

**Issue by Resseguie** [bocoup/johnny-five.org#39]
~~Does it make sense under platform support page to change to "Requires (wireless) tethering" to wifi platforms like spark and imp?~~

Several platforms say "requires tethering" but that semi-implies a USB cable. Should the wording be changed on wifi platforms (eg spark and imp) to say "requires (wireless) tethering" or something similar?

**Comment by rwaldron** [comment]
I don't follow, should we add that information?

**Comment by Resseguie** [comment]
Dang, looking back I edited my question and the result doesn't make sense. :/

Let me update the original... ^^^

**Comment by rwaldron** [comment]
Ah, I get it now—yes I agree

**Comment by rwaldron** [comment]
There's a "via" property that's not being used yet
