### ISSUE TITLE
J5 logo looks terrible in Firefox

### ISSUE THREAD

**Issue by rwaldron** [bocoup/johnny-five.org#40]

**Comment by leobalter** [comment]
Firefox render pngs doing a bilinear interpolation and that's why it looks terrible. Not even with the image-rendering property is possible to improve this image without replacing one with a better quality/dpi

**Comment by rwaldron** [comment]
:(

This is in Firefox Developer Edition (39.0a2 (2015-04-21)): 

![](http://i.gyazo.com/b9ffcf63cd7e9f805cf92beca5479807.png)

This is in Firefox (37.0.2)

![](http://i.gyazo.com/7c39f05422c27f54232d902c8338b512.png)

(Which actually looks better now that I updated)

**Comment by frxnz** [comment]
Firefox dev edition supports `picture`, so it's loading the SVG, but it's missing the font. Instead of exporting the SVG with a font, convert the text to path.

(the thick J5 is the fallback PNG)

**Comment by Wilto** [comment]
Ah man, I’m a dumbass; I never outlined the font in the SVG.

**Comment by rwaldron** [comment]
I'll convert them with idraw or whatever and see what's what.

**Comment by rwaldron** [comment]
Well, either I did it wrong, or it doesn't work. Someone else want to take a crack at it?

**Comment by Wilto** [comment]
http://wil.to/j5-logo.svg should do it.

![image](https://cloud.githubusercontent.com/assets/439942/7261401/5dac1c6c-e83f-11e4-94a8-312cdb51cc26.png)

**Comment by rwaldron** [comment]
Show off
